version: '3'
services:
  web:
    container_name: myapp-web
    build: .
    image: myapp-web:latest
    env_file:
      - .env
    networks: 
      - django
    ports:
      - 8000:8000
    volumes:
      - django:/app/data
  asgi:
    container_name: myapp-asgi
    build: .
    image: myapp-asgi:latest
    command: daphne -b 0.0.0.0 -p ${ASGI_PORT} djagoChatApp.asgi:application
    networks:
      - django-net
    ports:
      - ${ASGI_PORT}:${ASGI_PORT}
    volumes:
      - django-data:/app/data
    depends_on:
      - web
networks:
  django:
    name: django-net
volumes:
  django:
    name: django-data
